spring:
  data:
      mongodb:
          username: lurdharry
          password: lurdharry
          host: localhost
          port: 27017
          database: books
          authentication-database: admin
server:
  port: 8090