spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: lurdharry
    password: lurdharry
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8050

application:
  config:
    user-url: http://localhost:2222/users
    book-url: http://localhost:2222/books
