spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb:http://AUTH-SERVICE
          predicates:
            - Path=/auth/**,/admin/**
        - id: user-service
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/users/**

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 2222