spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb:http://AUTH-SERVICE
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: user-admin-service
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/admin/**
        - id: book-service
          uri: lb:http://BOOK-SERVICE
          predicates:
            - Path=/books/**
        - id: borrow-service
          uri: lb:http://BORROW-SERVICE
          predicates:
            - Path=/borrow/**
        - id: borrow-lines-service
          uri: lb:http://BORROW-SERVICE
          predicates:
            - Path=/borrow-lines/**
management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 2222