spring:
  data:
    mongodb:
      password: lurdharry
      username: lurdharry
      host: localhost
      port: 27017
      database: books
      authentication-database: admin

  kafka:
    consumer:
      bootstrap-servers:
        - localhost:9092
      group-id: borrowGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: BorrowOrderConfirmation:com.lurdharry.library.kafka.borrow.BorrowOrderConfirmation, BorrowStatusConfirmation:com.lurdharry.library.kafka.borrow.BorrowStatusConfirmation

  mail:
    host: localhost
    port: 1025
    username: lurdharry
    password: lurdharry
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled:true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

server:
  port: 8040