spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.server: DEBUG