services:
  postgres:
    container_name: library_ms_pg
    image: postgres
    environment:
      POSTGRES_USER: lurdharry
      POSTGRES_PASSWORD: lurdharry
      PGDATA: /var/lib/postgresql/data
    volumes:
      - library_pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - library-ms-net
    restart: unless-stopped

  pgadmin:
    container_name: library_ms_pg_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - library_pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - library-ms-net
    restart: unless-stopped

  mongodb:
    container_name: library_ms_mongodb
    image: mongo
    volumes:
      - library_mongo_data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: lurdharry
      MONGO_INITDB_ROOT_PASSWORD: lurdharry
    networks:
      - library-ms-net

  mongo-express:
    container_name: library_ms_mongo_express
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=lurdharry
      - ME_CONFIG_MONGODB_ADMINPASSWORD=lurdharry
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=lurdharry
      - ME_CONFIG_BASICAUTH_PASSWORD=lurdharry
    networks:
      - library-ms-net

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_MAX_CLIENT_CNXNS: 60
      ZOOKEEPER_SNAP_RETAIN_COUNT: 3
      ZOOKEEPER_PURGE_INTERVAL: 12
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: INFO
    networks:
      - library-ms-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: ms_kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    networks:
      - library-ms-net
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000

  mail-dev:
   container_name: ms_mail_dev
   image: maildev/maildev:latest
   ports:
     - 1080:1080
     - 1025:1025
   environment:
     MAILDEV_WEB_PORT: 1080
     MAILDEV_SMTP_PORT: 1025

networks:
  library-ms-net:

volumes:
  library_pg_data:
  library_pgadmin:
  library_mongo_data:
